[project]
name = "tagline"
description = "Audio tags, at a glance!"
version = "0.1.0"
requires-python = ">=3.14"
readme = "README.md"
authors = [{ name = "June", email = "junapur@proton.me" }]
dependencies = []

[project.urls]
Repository = "https://github.com/junapur/Tagline"
Issues = "https://github.com/junapur/Tagline/issues"
Changelog = "https://github.com/junapur/Tagline/blob/main/CHANGELOG.md"

[project.scripts]
tagline = "tagline:main"

[build-system]
requires = ["uv_build>=0.12.23, <0.13.0"]
build-backend = "uv_build"

[dependency-groups]
nox = [
    "nox-uv>=0.8.0",
]
type-check = [
    "pyrefly>=1.3.2",
]
lint = [
    "ruff>=0.16.10",
]

[tool.uv]
default-groups = "all"

[tool.pyrefly]
project-includes = ["**/*.py*"]
preset = "strict"
infer-with-first-use = false

[tool.ruff.lint]
select = [
    "ASYNC",   # flake8-async
    "S",       # flake8-bandit
    "BLE",     # flake8-blind-except
    "FBT",     # flake8-boolean-trap
    "B",       # flake8-bugbear
    "A",       # flake8-builtins
    "C4",      # flake8-comprehensions
    "DTZ",     # flake8-datetimez
    "T10",     # flake8-debugger
    "EM",      # flake8-errmsg
    "FA",      # flake8-future-annotations
    "ISC",     # flake8-implicit-str-concat
    "ICN",     # flake8-import-conventions
    "LOG",     # flake8-logging
    "G",       # flake8-logging-format
    "PIE",     # flake8-pie
    "PYI",     # flake8-pyi
    "PT",      # flake8-pytest-style
    "RSE",     # flake8-raise
    "RET",     # flake8-return
    "SLF",     # flake8-self
    "SIM",     # flake8-simplify
    "TID",     # flake8-tidy-imports
    "PTH",     # flake8-use-pathlib
    "FLY",     # flynt
    "I",       # isort
    "N",       # pep8-naming
    "PERF101", # perflint (unnecessary-list-cast)
    "PERF102", # perflint (incorrect-dict-iterator)
    "PERF402", # perflint (manual-list-copy)
    "E",       # pycodestyle (errors)
    "W605",    # pycodestyle (invalid-escape-sequence)
    "F",       # pyflakes
    "PLC",     # pylint (convention)
    "PLE",     # pylint (errors)
    "PLR",     # pylint (refactor)
    "PLW",     # pylint (warnings)
    "UP",      # pyupgrade
    "FURB",    # refurb
    "RUF",     # ruff rules
    "TRY",     # tryceratops
]

ignore = [
    # prefer rule codes over names in this file:
    "RUF201",
    # too-many-* rules:
    "PLR09",
    "PLR1702",
    # conflicts with ruff's formatter:
    "E111",
    "E114",
    "E117",
    "E501",
]
